AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Mark - mark-event-q
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ProcessDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sighware.mark.queue.DynamoDbStreamProcessor::handleRequest
      Runtime: java8
      CodeUri: s3://customer-record/00ad7258de296cbae78131837bbeeaab
      MemorySize: 1024
      Environment:
        Variables:
          FAN_OUT_SQS_QUEUE_URL:
            Ref: FanOutQueue
      Policies:
      - AWSLambdaDynamoDBExecutionRole
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue: DynamoDBStreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON
  FanOut:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sighware.mark.queue.FanOut::handleRequest
      Runtime: java8
      CodeUri: s3://customer-record/00ad7258de296cbae78131837bbeeaab
      MemorySize: 1024
      Environment:
        Variables:
          FAN_OUT_SQS_QUEUE_URL:
            Ref: FanOutQueue
      Events:
        SqsJobQueue:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - FanOutQueue
              - Arn
            BatchSize: 1
  FanOutQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MarkFanOutQueue.fifo
      FifoQueue: true
  FanOutQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: FanOutQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:*
          Resource: '*'
Outputs:
  QueueName:
    Description: Name of FanOutQueue SQS
    Value:
      Fn::GetAtt:
      - FanOutQueue
      - QueueName
  QueueARN:
    Description: ARN of FanOutQueue SQS
    Value:
      Fn::GetAtt:
      - FanOutQueue
      - Arn
