AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Mark - mark-event-queue

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  # Lambda listens to a DynamoDB stream on the RegistrationNumberEvent table and converts the
  # data to json. Wrirtes the json to the FanOut queue
  ProcessDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sighware.mark.queue.DynamoDbStreamProcessor::handleRequest
      Runtime: java8
      CodeUri: target/mark-event-queue.jar
      MemorySize: 1024
      Environment:
        Variables:
          FAN_OUT_SQS_QUEUE_URL: !Ref FanOutQueue
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaDynamoDBExecutionRole
        - AWSLambdaSQSQueueExecutionRole
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue DynamoDBStreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON

  FanOut:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sighware.mark.queue.FanOut::handleRequest
      Runtime: java8
      CodeUri: target/mark-event-queue.jar
      MemorySize: 1024
      Environment:
        Variables:
          FAN_OUT_SQS_QUEUE_URL: !Ref FanOutQueue
          FAN_CLIENT_OUT_SQS_QUEUE_URL: !Ref FanOutClientQueue
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaSQSQueueExecutionRole
      Events:
        FanOutJobQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt FanOutQueue.Arn
            BatchSize: 1

  FanOutQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MarkFanOutQueue.fifo
      FifoQueue: true

  FanOutQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FanOutQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: "*"

  FanOutClientQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MarkFanOutClientQueue.fifo
      FifoQueue: true

  FanOutClientQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FanOutClientQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: "*"

Outputs:
  QueueName:
    Description: "Name of FanOutQueue SQS"
    Value:
      Fn::GetAtt:
        - "FanOutQueue"
        - "QueueName"
  QueueARN:
    Description: "ARN of FanOutQueue SQS"
    Value:
      Fn::GetAtt:
        - "FanOutQueue"
        - "Arn"
  ClientQueueName:
    Description: "Name of client FanOutQueue SQS"
    Value:
      Fn::GetAtt:
        - "FanOutClientQueue"
        - "QueueName"
  ClientQueueARN:
    Description: "ARN of client FanOutQueue SQS"
    Value:
      Fn::GetAtt:
        - "FanOutClientQueue"
        - "Arn"
